#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &



bspc monitor DisplayPort-0 -d 1 2
bspc monitor HDMI-A-0 -d 3 4 5

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^4'
bspc rule -a Spotify desktop='^5'
bspc rule -a Zathura state=tile
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr
bspc config focus_follows_pointer true

# colors
bspc config focused_border_color "#fabd2f"




# master stack layout
bsp-layout set tall 1
bsp-layout set tall 2
bsp-layout set tall 3
bsp-layout set tall 4
bsp-layout set tall 5


polybar primary &
polybar secondary &
